[general]
## Project name. This is a required field.
name = "cp-library"

## Project version (in semver). This is a required field.
version = "0.7.5"

## Fix version requirement. Default is "*".
fix_version = "1.2.0"

## Project authors.
# authors = ["Alice", "Bob"]

# Project description.
description = "A library for competitive programming in Fixlang."

# Project license.
license = "CC0-1.0"

[build]
files = [
    "io/io.fix",
    "zp/zp.fix",
    "arithmetic/arithmetic.fix",
    "segtree/segtree.fix",
    "segtree/dsegtree.fix",
    "segtree/lsegtree.fix",
    "segtree/ldsegtree.fix",
    "trait/trait.fix",
    "unionfind/unionfind.fix",
    "graph/graph.fix",
    "convolution/convolution.fix",
    "maxflow/maxflow.fix",
    "bipartite/bipartite.fix",
    "mincostflow/mincostflow.fix",
    "twosat/twosat.fix",
    "string/string.fix",
    "bits/bits.fix",
    "misc/misc.fix",
]
objects = ["lib.o"]
preliminary_commands = [["make", "-s", "lib.o"]]

[build.test]
files = [
    "test.fix",
    "io/io-test.fix",
    "zp/zp-test.fix",
    "arithmetic/arithmetic-test.fix",
    "segtree/segtree-test.fix",
    "segtree/dsegtree-test.fix",
    "segtree/lsegtree-test.fix",
    "segtree/ldsegtree-test.fix",
    "unionfind/unionfind-test.fix",
    "graph/graph-test.fix",
    "convolution/convolution-test.fix",
    "maxflow/maxflow-test.fix",
    "bipartite/bipartite-test.fix",
    "twosat/twosat-test.fix",
    "mincostflow/mincostflow-test.fix",
    "string/string-test.fix",
    "bits/bits-test.fix",
    "misc/misc-test.fix",
]


[[dependencies]]
name = "random"
version = "1.1.1"
git = { url = "https://github.com/tttmmmyyyy/fixlang-random.git" }


[[dependencies]]
name = "binary-heap"
version = "0.2.0"
git = { url = "https://github.com/tttmmmyyyy/fixlang-binary-heap.git" }


[[dependencies]]
name = "bool-array"
version = "0.1.1"
git = { url = "https://github.com/tttmmmyyyy/bool-array.git" }


[[dependencies]]
name = "ring-buffer"
version = "0.1.0"
git = { url = "https://github.com/tttmmmyyyy/ring-buffer.git" }
